name: startup

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: setup colors
        run: TERM="xterm"

      - name: setup server
        run: chmod +x setup.sh && ./setup.sh --name minecraft --proceed true --version 1.19.4 --port 25565 --eula true --remove true --start false

      - name: startup server
        run: cd minecraft && chmod +x start.sh && ./start.sh --verbose
